// Generated by ReScript, PLEASE EDIT WITH CARE


var basePath = process.env.KRATOS_API;

var loginSelfServeEndpoint = basePath + "/self-service/login/browser";

var registrationSelfServeEndpoint = basePath + "/self-service/registration/browser";

var logoutSelfServeEndpoint = basePath + "/self-service/browser/flows/logout";

export {
  basePath ,
  loginSelfServeEndpoint ,
  registrationSelfServeEndpoint ,
  logoutSelfServeEndpoint ,
  
}
/* basePath Not a pure module */
