// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Unsafe = {};

function redirect(url) {
  var loc = typeof location === "undefined" ? undefined : location;
  if (loc !== undefined) {
    loc.href = url;
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: /* ErrorObjectNotFound */{
              _0: "Location object not found in global namespac."
            }
          };
  }
}

exports.Unsafe = Unsafe;
exports.redirect = redirect;
/* No side effect */
