version: '3.7'

services:
  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  kratos-migrate:
    depends_on:
      - postgresd
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ${PWD}/kratos/configs
        target: /etc/config/kratos
    command: ["migrate", "sql", "--read-from-env", "--config", "/etc/config/kratos/kratos.yaml", "--yes"]
    networks:
      - intranet

  kratos:
    depends_on:
        - kratos-migrate
    image: oryd/kratos:latest-sqlite
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: ["serve", "--config", "/etc/config/kratos/kratos.yaml", "--dev"]
    volumes:
      -
        type: bind
        source: ${PWD}/kratos/configs
        target: /etc/config/kratos
    ports:
      - 4434:4434
      - 4433:4433
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  # frontend:
  #   build: ../../frontend
  #   ports:
  #     - '3000:3000'
  #   # environment:
  #   #   - KRATOS_PUBLIC_URL=http://kratos:4433/
  #   #   - KRATOS_ADMIN_URL=http://kratos:4434/
  #   networks:
  #     - intranet
  #   # restart: on-failure

networks:
  intranet:
