// Generated by ReScript, PLEASE EDIT WITH CARE

import * as XHR from "../XHR.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Route from "./Route.bs.js";
import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function signOut(param) {
  window.location.href = "http://127.0.0.1:4433/self-service/browser/flows/logout";
  
}

function Dashboard(Props) {
  var match = React.useState(function () {
        
      });
  var setIdentity = match[1];
  var identity = match[0];
  React.useEffect((function () {
          XHR.whoami((function (res) {
                  var e = res.error;
                  if (e !== undefined) {
                    console.log(e);
                    if (e.code === 401) {
                      return RescriptReactRouter.push(Route.login);
                    } else {
                      return ;
                    }
                  } else {
                    return Curry._1(setIdentity, (function (_prev) {
                                  return res.identity;
                                }));
                  }
                }), (function (e) {
                  console.log(e);
                  
                }), undefined);
          
        }), []);
  return React.createElement("div", undefined, identity !== undefined ? React.createElement("div", {
                    className: "min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8"
                  }, React.createElement("div", {
                        className: "max-w-md w-full space-y-8"
                      }, React.createElement("h1", {
                            className: "mt-6 text-center text-3xl font-extrabold text-gray-900"
                          }, "Hello " + identity.traits.name.first + "!")), React.createElement("div", {
                        className: "mt-8 space-y-6"
                      }, React.createElement("button", {
                            className: "inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
                            onClick: (function (_event) {
                                return signOut(undefined);
                              })
                          }, "Sign out"))) : null);
}

var make = Dashboard;

export {
  signOut ,
  make ,
  
}
/* react Not a pure module */
