// Generated by ReScript, PLEASE EDIT WITH CARE

import * as XHR from "../XHR.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Dashboard(Props) {
  var match = React.useState(function () {
        
      });
  var setIdentity = match[1];
  var identity = match[0];
  React.useEffect((function () {
          XHR.whoami((function (res) {
                  return Curry._1(setIdentity, (function (_prev) {
                                return res.identity;
                              }));
                }), (function (err) {
                  console.log(err);
                  
                }), undefined);
          
        }), []);
  if (identity !== undefined) {
    return React.createElement("h1", undefined, "Hello " + identity.traits.name.first + "!");
  } else {
    return null;
  }
}

var make = Dashboard;

export {
  make ,
  
}
/* react Not a pure module */
