// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Registration = {
  title: "Registration",
  submitButtonLabel: "Registration"
};

var Login = {
  title: "Sign in",
  submitButtonLabel: "Sign in",
  forgotPasswordLabel: "Forgot your password?"
};

var Recovery = {
  title: "Recover Password"
};

exports.Registration = Registration;
exports.Login = Login;
exports.Recovery = Recovery;
/* No side effect */
