// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function NotFound(Props) {
  return React.createElement("div", undefined, "NOT FOUND");
}

var make = NotFound;

exports.make = make;
/* react Not a pure module */
