// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Url = require("../Url.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var Route = require("./Route.bs.js");
var React = require("react");
var Kratos = require("../Bindings/Kratos.bs.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var $$Promise = require("reason-promise/src/js/promise.bs.js");
var Belt_Map = require("rescript/lib/js/belt_Map.js");
var KratosClient = require("@ory/kratos-client");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

var opts = {
  basePath: Kratos.basePath
};

var api = new KratosClient.PublicApi(new KratosClient.Configuration(opts));

function renderInputs(fields) {
  return fields.map(function (field) {
              return React.createElement(React.Fragment, undefined, React.createElement("label", {
                              key: field.name,
                              className: "sr-only"
                            }, field.type !== "hidden" ? field.name : ""), React.createElement("input", {
                              defaultValue: field.value,
                              className: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm",
                              name: field.name,
                              placeholder: field.name,
                              required: field.required,
                              type: field.type
                            }));
            });
}

function renderMessages(messages) {
  if (messages !== undefined) {
    return messages;
  } else {
    return [];
  }
}

function Register(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        return {};
      });
  var setMethods = match[1];
  React.useEffect((function () {
          var id = Belt_Map.get(Url.parseSearchParams(url), "flow");
          if (id !== undefined) {
            $$Promise.get($$Promise.Js.$$catch(api.getSelfServiceRegistrationFlow(id), (function (err) {
                        console.log(err);
                        RescriptReactRouter.push(Route.register);
                        return $$Promise.Js.rejected(err);
                      })), (function (res) {
                    console.log(res);
                    if (res.status !== 200) {
                      RescriptReactRouter.push(Route.register);
                    }
                    return Curry._1(setMethods, (function (_prev) {
                                  return res.data.methods;
                                }));
                  }));
          } else {
            window.location.href = Kratos.registrationSelfServeEndpoint;
          }
          
        }), []);
  var loginForms = Js_dict.values(match[0]).map(function (method) {
        var messages = method.config.messages;
        return React.createElement("div", undefined, React.createElement("div", undefined, (
                          messages !== undefined ? messages : []
                        ).map(function (m) {
                            return React.createElement("p", {
                                        key: String(m.id)
                                      }, m.text);
                          })), React.createElement("form", {
                        className: "mt-8 space-y-6",
                        action: method.config.action,
                        method: method.config.method
                      }, renderInputs(method.config.fields), React.createElement("button", {
                            className: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
                            type: "submit"
                          }, "Register")));
      });
  return React.createElement("div", {
              className: "min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8"
            }, React.createElement("div", {
                  className: "max-w-md w-full space-y-8"
                }, React.createElement("div", undefined, React.createElement("h1", {
                          className: "mt-6 text-center text-3xl font-extrabold text-gray-900"
                        }, "Registration")), loginForms));
}

var selfServeEndpoint = Kratos.registrationSelfServeEndpoint;

var make = Register;

exports.selfServeEndpoint = selfServeEndpoint;
exports.opts = opts;
exports.api = api;
exports.renderInputs = renderInputs;
exports.renderMessages = renderMessages;
exports.make = make;
/* api Not a pure module */
