// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Url = require("../Url.bs.js");
var Form = require("../Components/Form.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var Route = require("./Route.bs.js");
var React = require("react");
var $$Window = require("../Bindings/Window.bs.js");
var $$Promise = require("reason-promise/src/js/promise.bs.js");
var Belt_Map = require("rescript/lib/js/belt_Map.js");
var Messages = require("./Messages.bs.js");
var KratosClient = require("../KratosClient.bs.js");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

function Register(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        
      });
  var setMethods = match[1];
  var methods = match[0];
  var match$1 = React.useState(function () {
        return Belt_Map.get(Url.parseSearchParams(url), "flow");
      });
  var setFlowID = match$1[1];
  React.useEffect((function () {
          var id = Belt_Map.get(Url.parseSearchParams(url), "flow");
          if (id !== undefined) {
            $$Promise.get($$Promise.Js.toResult(KratosClient.api.getSelfServiceRegistrationFlow(id)), (function (res) {
                    console.log(res);
                    if (res.TAG === /* Ok */0) {
                      var payload = res._0;
                      return Curry._1(setMethods, (function (_prev) {
                                    return payload.data.ui;
                                  }));
                    }
                    var match = res._0.response.status;
                    if (match !== 410) {
                      return RescriptReactRouter.push("/login");
                    } else {
                      return Curry._1(setFlowID, (function (_prev) {
                                    
                                  }));
                    }
                  }));
          } else {
            var e = $$Window.redirect(KratosClient.registrationSelfServeEndpoint + Url.forwardSearchParams(url));
            if (e.TAG === /* Ok */0) {
              console.log("Window location set but page redirect failed.");
            } else {
              console.log(e._0);
            }
          }
          
        }), [match$1[0]]);
  if (methods !== undefined) {
    var m = methods.messages;
    return React.createElement("div", {
                className: "min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8"
              }, React.createElement("div", {
                    className: "max-w-md w-full space-y-8"
                  }, React.createElement("div", undefined, React.createElement("h2", {
                            className: "mt-6 text-center text-3xl font-extrabold text-gray-900"
                          }, Messages.Registration.title), React.createElement("p", {
                            className: "mt-2 text-center text-sm text-gray-600"
                          }, "Or ", React.createElement("a", {
                                className: "font-medium text-indigo-600 hover:text-indigo-500",
                                href: "#",
                                onClick: (function (param) {
                                    return RescriptReactRouter.push(Route.login);
                                  })
                              }, "login"))), m !== undefined ? m.map(function (m) {
                          return React.createElement("p", {
                                      key: String(m.id)
                                    }, m.text);
                        }) : null, React.createElement(Form.make, {
                        ui: methods
                      })));
  } else {
    return null;
  }
}

var make = Register;

exports.make = make;
/* Url Not a pure module */
