// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DynamicInput = require("./DynamicInput.bs.js");

function DynamicInputList(Props) {
  var nodes = Props.nodes;
  return nodes.map(function (node) {
              var match = node.type;
              if (match === "input") {
                return React.createElement(DynamicInput.make, {
                            node: node
                          });
              } else {
                return null;
              }
            });
}

var make = DynamicInputList;

exports.make = make;
/* react Not a pure module */
