// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DynamicInput = require("./DynamicInput.bs.js");

function DynamicInputList(Props) {
  var fields = Props.fields;
  return fields.map(function (field) {
              return React.createElement(DynamicInput.make, {
                          field: field
                        });
            });
}

var make = DynamicInputList;

exports.make = make;
/* react Not a pure module */
