// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("rescript/lib/js/caml_option.js");
var DynamicInputList = require("./DynamicInputList.bs.js");

function Form(Props) {
  var ui = Props.ui;
  var childrenOpt = Props.children;
  var children = childrenOpt !== undefined ? Caml_option.valFromOption(childrenOpt) : null;
  return React.createElement("form", {
              className: "mt-8 space-y-6",
              action: ui.action,
              method: ui.method
            }, React.createElement("div", {
                  className: "mt-8 space-y-6"
                }, React.createElement(DynamicInputList.make, {
                      nodes: ui.nodes
                    })), React.createElement("div", {
                  className: "flex items-center justify-between"
                }, React.createElement("div", {
                      className: "text-sm"
                    }, children)), React.createElement("div", undefined));
}

var make = Form;

exports.make = make;
/* react Not a pure module */
