// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("rescript/lib/js/caml_option.js");
var DynamicInputList = require("./DynamicInputList.bs.js");

function Form(Props) {
  var method = Props.method;
  var submitButtonLabel = Props.submitButtonLabel;
  var childrenOpt = Props.children;
  var children = childrenOpt !== undefined ? Caml_option.valFromOption(childrenOpt) : null;
  return React.createElement("form", {
              className: "mt-8 space-y-6",
              action: method.config.action,
              method: method.config.method
            }, React.createElement("div", {
                  className: "mt-8 space-y-6"
                }, React.createElement(DynamicInputList.make, {
                      fields: method.config.fields
                    })), React.createElement("div", {
                  className: "flex items-center justify-between"
                }, React.createElement("div", {
                      className: "text-sm"
                    }, children)), React.createElement("div", undefined, React.createElement("button", {
                      className: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
                      type: "submit"
                    }, submitButtonLabel)));
}

var make = Form;

exports.make = make;
/* react Not a pure module */
