// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "./Pages/Login.bs.js";
import * as React from "react";
import * as NotFound from "./Pages/NotFound.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    if (match.hd === "login") {
      if (match.tl) {
        return React.createElement(NotFound.make, {});
      } else {
        return React.createElement(Login.make, {});
      }
    } else {
      return React.createElement(NotFound.make, {});
    }
  } else {
    return React.createElement("h1", undefined, "Dashboard Home");
  }
}

var make = App;

export {
  make ,
  
}
/* Login Not a pure module */
