// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "./Pages/Login.bs.js";
import * as React from "react";
import * as NotFound from "./Pages/NotFound.bs.js";
import * as Register from "./Pages/Register.bs.js";
import * as Dashboard from "./Pages/Dashboard.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

import './app.css'
;

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement(Dashboard.make, {});
  }
  switch (match.hd) {
    case "login" :
        if (!match.tl) {
          return React.createElement(Login.make, {});
        }
        break;
    case "register" :
        if (!match.tl) {
          return React.createElement(Register.make, {});
        }
        break;
    default:
      
  }
  return React.createElement(NotFound.make, {});
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
