// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var element = document.querySelector("#root");

if (!(element == null)) {
  ReactDom.render(React.createElement(App.make, {}), element);
}

export {
  
}
/* element Not a pure module */
