// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

import './styles/main.css'
;

var element = document.querySelector("#root");

if (!(element == null)) {
  ReactDom.render(React.createElement(App.make, {}), element);
}

/*  Not a pure module */
