// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var KratosClient = require("@ory/kratos-client");

var opts = {
  basePath: Belt_Option.getWithDefault(Caml_option.nullable_to_opt(process.env.KRATOS_API), "")
};

var api = new KratosClient.PublicApi(new KratosClient.Configuration(opts));

var recoverySelfServeEndpoint = opts.basePath + "/self-service/recovery/browser";

var loginSelfServeEndpoint = opts.basePath + "/self-service/login/browser";

var registrationSelfServeEndpoint = opts.basePath + "/self-service/registration/browser";

var logoutSelfServeEndpoint = opts.basePath + "/self-service/browser/flows/logout";

exports.opts = opts;
exports.api = api;
exports.recoverySelfServeEndpoint = recoverySelfServeEndpoint;
exports.loginSelfServeEndpoint = loginSelfServeEndpoint;
exports.registrationSelfServeEndpoint = registrationSelfServeEndpoint;
exports.logoutSelfServeEndpoint = logoutSelfServeEndpoint;
/* opts Not a pure module */
