// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LoginForm(Props) {
  return React.createElement("form", undefined, React.createElement("label", undefined, "Email", React.createElement("input", {
                      name: "email",
                      type: "text"
                    })), React.createElement("label", undefined, "Password", React.createElement("input", {
                      name: "password",
                      type: "text"
                    })), React.createElement("input", {
                  type: "submit",
                  value: "Submit"
                }));
}

var make = LoginForm;

export {
  make ,
  
}
/* react Not a pure module */
