// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("rescript/lib/js/belt_Id.js");
var Belt_Map = require("rescript/lib/js/belt_Map.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var cmp = Caml_obj.caml_compare;

var SearchKeyCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

function parseSearchParams(url) {
  return url.search.split("&").filter(function (v) {
                return Caml_option.null_to_opt(v.match(/.*=.*/)) !== undefined;
              }).reduce((function (acc, item) {
                var kv = item.split("=");
                return Belt_Map.set(acc, Caml_array.get(kv, 0), Caml_array.get(kv, 1));
              }), Belt_Map.make(SearchKeyCmp));
}

function forwardSearchParams(url) {
  if (url.search === "") {
    return url.search;
  } else {
    return "?" + url.search;
  }
}

exports.SearchKeyCmp = SearchKeyCmp;
exports.parseSearchParams = parseSearchParams;
exports.forwardSearchParams = forwardSearchParams;
/* SearchKeyCmp Not a pure module */
