// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function whoami(onDone, onError, param) {
  var request = new XMLHttpRequest();
  request.addEventListener("load", (function (param) {
          return Curry._1(onDone, JSON.parse(request.response));
        }));
  request.addEventListener("error", (function (param) {
          return Curry._1(onError, JSON.parse(request.response));
        }));
  request.withCredentials = true;
  request.open("GET", "http://127.0.0.1:4433/sessions/whoami");
  request.send();
  
}

export {
  whoami ,
  
}
/* No side effect */
