// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Kratos = require("./Bindings/Kratos.bs.js");

function whoami(onDone, onError, param) {
  var request = new XMLHttpRequest();
  request.addEventListener("load", (function (param) {
          return Curry._1(onDone, JSON.parse(request.response));
        }));
  request.addEventListener("error", (function (param) {
          return Curry._1(onError, JSON.parse(request.response));
        }));
  request.withCredentials = true;
  request.open("GET", Kratos.whoamiEndpoint);
  request.send();
  
}

exports.whoami = whoami;
/* Kratos Not a pure module */
