name: ReScript UI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - run: npm ci
      - name: Run Unit Tests
        run: npm run ci:test
