name: ReScript UI
on:
  push:
    branches: [ main ]
jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - run: npm ci
      - run: npm run ci:test
      - run: NODENV=production npx -- parcel build index.html --dist-dir public
      - run: |
          docker-compose -f kratos/docker-compose.yaml -f kratos/docker-compose-e2e.yaml up -d --build --force-recreate
          npm run test:e2e
          docker-compose -f kratos/docker-compose.yaml -f kratos/docker-compose-e2e.yaml down
